/*
 * Copyright 2023-2025 Attila Fazekas & contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@file:OptIn(ExperimentalCompilerApi::class)

package dev.kolibrium.api.ksp.processors

import com.tschuchort.compiletesting.KotlinCompilation.ExitCode.COMPILATION_ERROR
import com.tschuchort.compiletesting.KotlinCompilation.ExitCode.OK
import com.tschuchort.compiletesting.SourceFile.Companion.kotlin
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi
import org.junit.jupiter.api.Test

class AuthenticationCodeGenerationTest : ApiBaseTest() {
    @Test
    fun `BEARER generates token context parameter and bearerAuth call`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import dev.kolibrium.api.ksp.annotations.AuthType
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Auth(type = AuthType.BEARER)
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        assertSourceEquals(
            $$"""
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.api.ksp.test.generated

            import dev.kolibrium.api.core.ApiResponse
            import dev.kolibrium.api.ksp.test.models.UserDto
            import io.ktor.client.HttpClient
            import io.ktor.client.call.body
            import io.ktor.client.request.`get`
            import io.ktor.client.request.bearerAuth
            import io.ktor.http.contentType
            import kotlin.String

            /**
             * HTTP client for the Test API.
             */
            public class TestClient(
              private val client: HttpClient,
              private val baseUrl: String,
            ) {
              /**
               * Performs a GET request to /users.
               */
              context(token: String)
              public suspend fun getUsers(): ApiResponse<UserDto> {
                val httpResponse = client.get("$baseUrl/users") {
                  bearerAuth(token)
                }

                return ApiResponse(
                  status = httpResponse.status,
                  headers = httpResponse.headers,
                  contentType = httpResponse.contentType(),
                  body = httpResponse.body(),
                )
              }
            }
            """,
            "TestClient.kt",
            kotlinCompilation,
        )
    }

    @Test
    fun `BASIC generates username and password context parameters and basicAuth call`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import dev.kolibrium.api.ksp.annotations.AuthType
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Auth(type = AuthType.BASIC)
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        assertSourceEquals(
            $$"""
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.api.ksp.test.generated

            import dev.kolibrium.api.core.ApiResponse
            import dev.kolibrium.api.ksp.test.models.UserDto
            import io.ktor.client.HttpClient
            import io.ktor.client.call.body
            import io.ktor.client.request.`get`
            import io.ktor.client.request.basicAuth
            import io.ktor.http.contentType
            import kotlin.String

            /**
             * HTTP client for the Test API.
             */
            public class TestClient(
              private val client: HttpClient,
              private val baseUrl: String,
            ) {
              /**
               * Performs a GET request to /users.
               */
              context(username: String, password: String)
              public suspend fun getUsers(): ApiResponse<UserDto> {
                val httpResponse = client.get("$baseUrl/users") {
                  basicAuth(username, password)
                }

                return ApiResponse(
                  status = httpResponse.status,
                  headers = httpResponse.headers,
                  contentType = httpResponse.contentType(),
                  body = httpResponse.body(),
                )
              }
            }
            """,
            "TestClient.kt",
            kotlinCompilation,
        )
    }

    @Test
    fun `API_KEY generates apiKey context parameter with default X-API-Key header`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import dev.kolibrium.api.ksp.annotations.AuthType
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Auth(type = AuthType.API_KEY)
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        assertSourceEquals(
            $$"""
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.api.ksp.test.generated

            import dev.kolibrium.api.core.ApiResponse
            import dev.kolibrium.api.ksp.test.models.UserDto
            import io.ktor.client.HttpClient
            import io.ktor.client.call.body
            import io.ktor.client.request.`get`
            import io.ktor.client.request.`header`
            import io.ktor.http.contentType
            import kotlin.String

            /**
             * HTTP client for the Test API.
             */
            public class TestClient(
              private val client: HttpClient,
              private val baseUrl: String,
            ) {
              /**
               * Performs a GET request to /users.
               */
              context(apiKey: String)
              public suspend fun getUsers(): ApiResponse<UserDto> {
                val httpResponse = client.get("$baseUrl/users") {
                  header("X-API-Key", apiKey)
                }

                return ApiResponse(
                  status = httpResponse.status,
                  headers = httpResponse.headers,
                  contentType = httpResponse.contentType(),
                  body = httpResponse.body(),
                )
              }
            }
            """,
            "TestClient.kt",
            kotlinCompilation,
        )
    }

    @Test
    fun `API_KEY with custom valid headerName`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import dev.kolibrium.api.ksp.annotations.AuthType
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Auth(type = AuthType.API_KEY, headerName = "Authorization")
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        assertSourceEquals(
            $$"""
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.api.ksp.test.generated

            import dev.kolibrium.api.core.ApiResponse
            import dev.kolibrium.api.ksp.test.models.UserDto
            import io.ktor.client.HttpClient
            import io.ktor.client.call.body
            import io.ktor.client.request.`get`
            import io.ktor.client.request.`header`
            import io.ktor.http.contentType
            import kotlin.String

            /**
             * HTTP client for the Test API.
             */
            public class TestClient(
              private val client: HttpClient,
              private val baseUrl: String,
            ) {
              /**
               * Performs a GET request to /users.
               */
              context(apiKey: String)
              public suspend fun getUsers(): ApiResponse<UserDto> {
                val httpResponse = client.get("$baseUrl/users") {
                  header("Authorization", apiKey)
                }

                return ApiResponse(
                  status = httpResponse.status,
                  headers = httpResponse.headers,
                  contentType = httpResponse.contentType(),
                  body = httpResponse.body(),
                )
              }
            }
            """,
            "TestClient.kt",
            kotlinCompilation,
        )
    }

    @Test
    fun `API_KEY with invalid headerName rejected`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import dev.kolibrium.api.ksp.annotations.AuthType
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Auth(type = AuthType.API_KEY, headerName = "Invalid Header Name")
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "Invalid API key header name"
    }

    @Test
    fun `CUSTOM generates lambda context parameter and customAuth call`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import dev.kolibrium.api.ksp.annotations.AuthType
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Auth(type = AuthType.CUSTOM)
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        assertSourceEquals(
            $$"""
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.api.ksp.test.generated

            import dev.kolibrium.api.core.ApiResponse
            import dev.kolibrium.api.ksp.test.models.UserDto
            import io.ktor.client.HttpClient
            import io.ktor.client.call.body
            import io.ktor.client.request.HttpRequestBuilder
            import io.ktor.client.request.`get`
            import io.ktor.http.contentType
            import kotlin.String
            import kotlin.Unit

            /**
             * HTTP client for the Test API.
             */
            public class TestClient(
              private val client: HttpClient,
              private val baseUrl: String,
            ) {
              /**
               * Performs a GET request to /users.
               */
              context(customAuth: HttpRequestBuilder.() -> Unit)
              public suspend fun getUsers(): ApiResponse<UserDto> {
                val httpResponse = client.get("$baseUrl/users") {
                  customAuth()
                }

                return ApiResponse(
                  status = httpResponse.status,
                  headers = httpResponse.headers,
                  contentType = httpResponse.contentType(),
                  body = httpResponse.body(),
                )
              }
            }
            """,
            "TestClient.kt",
            kotlinCompilation,
        )
    }

    @Test
    fun `headerName used with non-API_KEY auth type rejected`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import dev.kolibrium.api.ksp.annotations.AuthType
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Auth(type = AuthType.BEARER, headerName = "X-Custom")
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "headerName parameter can only be used with AuthType.API_KEY"
    }

    @Test
    fun `Multiple requests with different auth types generate all required auth imports`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import dev.kolibrium.api.ksp.annotations.AuthType
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Auth(type = AuthType.BEARER)
                @Serializable
                object GetUsersRequest
                @GET("/orders")
                @Returns(success = UserDto::class)
                @Auth(type = AuthType.BASIC)
                @Serializable
                object GetOrdersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        val source = kotlinCompilation.getGeneratedSource("TestClient.kt")
        source shouldContain "import io.ktor.client.request.bearerAuth"
        source shouldContain "import io.ktor.client.request.basicAuth"
    }

    @Test
    fun `NONE generates no context parameters or auth logic`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        assertSourceEquals(
            $$"""
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.api.ksp.test.generated

            import dev.kolibrium.api.core.ApiResponse
            import dev.kolibrium.api.ksp.test.models.UserDto
            import io.ktor.client.HttpClient
            import io.ktor.client.call.body
            import io.ktor.client.request.`get`
            import io.ktor.http.contentType
            import kotlin.String

            /**
             * HTTP client for the Test API.
             */
            public class TestClient(
              private val client: HttpClient,
              private val baseUrl: String,
            ) {
              /**
               * Performs a GET request to /users.
               */
              public suspend fun getUsers(): ApiResponse<UserDto> {
                val httpResponse = client.get("$baseUrl/users")

                return ApiResponse(
                  status = httpResponse.status,
                  headers = httpResponse.headers,
                  contentType = httpResponse.contentType(),
                  body = httpResponse.body(),
                )
              }
            }
            """,
            "TestClient.kt",
            kotlinCompilation,
        )
    }
}
