/*
 * Copyright 2023-2025 Attila Fazekas & contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@file:OptIn(ExperimentalCompilerApi::class)

package dev.kolibrium.api.ksp.processors

import com.tschuchort.compiletesting.KotlinCompilation.ExitCode.OK
import com.tschuchort.compiletesting.SourceFile.Companion.kotlin
import com.tschuchort.compiletesting.kspSourcesDir
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi
import org.junit.jupiter.api.Test

class GeneratedTestHarnessTest : ApiBaseTest() {
    @Test
    fun `Test harness file name, package, and header`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        val source = kotlinCompilation.getGeneratedSource("TestTestHarness.kt")
        source shouldContain "// Code generated by kolibrium-codegen. Do not edit."
        source shouldContain "package dev.kolibrium.api.ksp.test.generated"
    }

    @Test
    fun `Simple and setUp-tearDown overload signatures and delegation`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        val source = kotlinCompilation.getGeneratedSource("TestTestHarness.kt")
        source shouldContain "fun testApiTest("
        source shouldContain "baseUrl: String = TestApiSpec.baseUrl"
        source shouldContain "client: HttpClient = TestApiSpec.httpClient"
        source shouldContain "block: suspend TestClient.() -> Unit"
        source shouldContain "apiTest(api = TestClient(client, baseUrl), block = block)"
        source shouldContain "fun <T> testApiTest("
        source shouldContain "setUp: suspend TestClient.() -> T"
        source shouldContain "tearDown: suspend TestClient.(T) -> Unit = {}"
        source shouldContain "block: suspend TestClient.(T) -> Unit"
        source shouldContain "apiTest(api = TestClient(client, baseUrl), setUp = setUp, tearDown = tearDown, block = block)"
    }

    @Test
    fun `generateTestHarness = false skips test harness generation`() {
        val noHarnessApiSpec =
            kotlin(
                "NoHarnessApiSpec.kt",
                """
                package dev.kolibrium.api.ksp.test
                import dev.kolibrium.api.core.ApiSpec
                import dev.kolibrium.api.ksp.annotations.GenerateApi
                @GenerateApi(generateTestHarness = false)
                object NoHarnessApiSpec : ApiSpec() {
                    override val baseUrl = "https://test.api"
                }
                """.trimIndent(),
            )
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(noHarnessApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        // Client should still be generated
        val clientSource = kotlinCompilation.getGeneratedSource("NoHarnessClient.kt")
        clientSource shouldContain "class NoHarnessClient"
        // But test harness should NOT be generated
        shouldThrow<IllegalArgumentException> {
            kotlinCompilation.getGeneratedSource("NoHarnessTestHarness.kt")
        }
    }

    @Test
    fun `GenerateApi with custom scanPackages discovers request classes in specified package`() {
        val apiSpec =
            kotlin(
                "CustomScanApiSpec.kt",
                """
                package dev.kolibrium.api.ksp.test
                import dev.kolibrium.api.core.ApiSpec
                import dev.kolibrium.api.ksp.annotations.GenerateApi
                @GenerateApi(scanPackages = ["dev.kolibrium.api.ksp.test.custom"])
                object CustomScanApiSpec : ApiSpec() {
                    override val baseUrl = "https://test.api"
                }
                """.trimIndent(),
            )
        val request =
            kotlin(
                "CustomRequests.kt",
                """
                package dev.kolibrium.api.ksp.test.custom
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(apiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        val clientSource = kotlinCompilation.getGeneratedSource("CustomScanClient.kt")
        clientSource shouldContain "class CustomScanClient"
        clientSource shouldContain "suspend fun getUsers"
    }

    @Test
    fun `GenerateApi with ByPrefix grouping produces grouped clients`() {
        val apiSpec =
            kotlin(
                "GroupedApiSpec.kt",
                """
                package dev.kolibrium.api.ksp.test
                import dev.kolibrium.api.core.ApiSpec
                import dev.kolibrium.api.ksp.annotations.ClientGrouping
                import dev.kolibrium.api.ksp.annotations.GenerateApi
                @GenerateApi(grouping = ClientGrouping.ByPrefix)
                object GroupedApiSpec : ApiSpec() {
                    override val baseUrl = "https://test.api"
                }
                """.trimIndent(),
            )
        val request =
            kotlin(
                "GroupedRequests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                object GetUsersRequest
                @Serializable
                data class OrderDto(val id: Int)
                @GET("/orders")
                @Returns(success = OrderDto::class)
                @Serializable
                object GetOrdersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(apiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        val usersClient = kotlinCompilation.getGeneratedSource("UsersClient.kt")
        usersClient shouldContain "class UsersClient"
        usersClient shouldContain "suspend fun getUsers"
        val ordersClient = kotlinCompilation.getGeneratedSource("OrdersClient.kt")
        ordersClient shouldContain "class OrdersClient"
        ordersClient shouldContain "suspend fun getOrders"
        // Root aggregator client should reference group clients
        val rootClient = kotlinCompilation.getGeneratedSource("GroupedClient.kt")
        rootClient shouldContain "class GroupedClient"
    }

    @Test
    fun `GenerateApi absent skips code generation`() {
        val apiSpec =
            kotlin(
                "DefaultApiSpec.kt",
                """
                package dev.kolibrium.api.ksp.test
                import dev.kolibrium.api.core.ApiSpec
                object DefaultApiSpec : ApiSpec() {
                    override val baseUrl = "https://test.api"
                }
                """.trimIndent(),
            )
        val request =
            kotlin(
                "DefaultRequests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                class GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(apiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        // No @GenerateApi means no code generation
        kotlinCompilation.kspSourcesDir
            .walkTopDown()
            .filter { it.isFile }
            .toList() shouldBe emptyList()
    }

    @Test
    fun `GenerateApi with empty scanPackages uses convention default`() {
        val apiSpec =
            kotlin(
                "EmptyScanApiSpec.kt",
                """
                package dev.kolibrium.api.ksp.test
                import dev.kolibrium.api.core.ApiSpec
                import dev.kolibrium.api.ksp.annotations.GenerateApi
                @GenerateApi(scanPackages = [])
                object EmptyScanApiSpec : ApiSpec() {
                    override val baseUrl = "https://test.api"
                }
                """.trimIndent(),
            )
        val request =
            kotlin(
                "EmptyScanRequests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                object GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(apiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        val clientSource = kotlinCompilation.getGeneratedSource("EmptyScanClient.kt")
        clientSource shouldContain "class EmptyScanClient"
        clientSource shouldContain "suspend fun getUsers"
    }
}
