/*
 * Copyright 2023-2025 Attila Fazekas & contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@file:OptIn(ExperimentalCompilerApi::class)

package dev.kolibrium.api.ksp.processors

import com.tschuchort.compiletesting.KotlinCompilation.ExitCode.COMPILATION_ERROR
import com.tschuchort.compiletesting.KotlinCompilation.ExitCode.OK
import com.tschuchort.compiletesting.SourceFile.Companion.kotlin
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi
import org.junit.jupiter.api.Test

class PathParameterValidationTest : ApiBaseTest() {
    @Test
    fun `Valid Path property resolves path variable`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                import kotlinx.serialization.Transient
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users/{id}")
                @Returns(success = UserDto::class)
                @Serializable
                data class GetUserRequest(@Path @Transient val id: Int = 0)
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        assertSourceEquals(
            $$"""
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.api.ksp.test.generated

            import dev.kolibrium.api.core.ApiResponse
            import dev.kolibrium.api.ksp.test.models.UserDto
            import io.ktor.client.HttpClient
            import io.ktor.client.call.body
            import io.ktor.client.request.`get`
            import io.ktor.http.contentType
            import io.ktor.http.encodeURLPathPart
            import kotlin.Int
            import kotlin.String

            /**
             * HTTP client for the Test API.
             */
            public class TestClient(
              private val client: HttpClient,
              private val baseUrl: String,
            ) {
              /**
               * Performs a GET request to /users/{id}.
               *
               * @param id path parameter — substituted into `/users/{id}`
               */
              public suspend fun getUser(id: Int): ApiResponse<UserDto> {
                val httpResponse = client.get("$baseUrl/users/${id.toString().encodeURLPathPart()}")

                return ApiResponse(
                  status = httpResponse.status,
                  headers = httpResponse.headers,
                  contentType = httpResponse.contentType(),
                  body = httpResponse.body(),
                )
              }
            }
            """,
            "TestClient.kt",
            kotlinCompilation,
        )
    }

    @Test
    fun `Path variable with no matching Path property rejected`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users/{id}")
                @Returns(success = UserDto::class)
                @Serializable
                class GetUserRequest
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "has no matching @Path parameter"
    }

    @Test
    fun `Path property not present in path rejected`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                import kotlinx.serialization.Transient
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users/{id}")
                @Returns(success = UserDto::class)
                @Serializable
                data class GetUserRequest(
                    @Path @Transient val id: Int = 0,
                    @Path @Transient val foo: String = ""
                )
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "not found in path"
    }

    @Test
    fun `Invalid path variable name rejected`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users/{123bad}")
                @Returns(success = UserDto::class)
                @Serializable
                class GetUserRequest
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "is not a valid Kotlin identifier"
    }

    @Test
    fun `Missing Transient on Path property rejected`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users/{id}")
                @Returns(success = UserDto::class)
                @Serializable
                data class GetUserRequest(@Path val id: Int = 0)
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "must be annotated with @Transient"
    }

    @Test
    fun `Property annotated with both Path and Query rejected`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                import kotlinx.serialization.Transient
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users/{id}")
                @Returns(success = UserDto::class)
                @Serializable
                data class GetUserRequest(@Path @Query @Transient val id: Int = 0)
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "cannot have multiple parameter annotations (@Path, @Query, @Header)"
    }

    @Test
    fun `Valid path parameter types accepted`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                import kotlinx.serialization.Transient
                @Serializable
                data class UserDto(val id: Int)
                @GET("/a/{s}/{i}/{l}/{sh}/{f}/{d}/{b}")
                @Returns(success = UserDto::class)
                @Serializable
                data class GetAllTypesRequest(
                    @Path @Transient val s: String = "",
                    @Path @Transient val i: Int = 0,
                    @Path @Transient val l: Long = 0L,
                    @Path @Transient val sh: Short = 0,
                    @Path @Transient val f: Float = 0f,
                    @Path @Transient val d: Double = 0.0,
                    @Path @Transient val b: Boolean = false
                )
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe OK
    }

    @Test
    fun `Invalid path parameter type rejected`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                import kotlinx.serialization.Transient
                @Serializable
                data class UserDto(val id: Int)
                data class CustomType(val value: String)
                @GET("/users/{id}")
                @Returns(success = UserDto::class)
                @Serializable
                data class GetUserRequest(@Path @Transient val id: CustomType = CustomType(""))
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "must be String, Int, Long, Short, Float, Double, or Boolean"
    }
}
