/*
 * Copyright 2023-2025 Attila Fazekas & contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@file:OptIn(ExperimentalCompilerApi::class)

package dev.kolibrium.api.ksp.processors

import com.tschuchort.compiletesting.KotlinCompilation.ExitCode.COMPILATION_ERROR
import com.tschuchort.compiletesting.KotlinCompilation.ExitCode.OK
import com.tschuchort.compiletesting.SourceFile.Companion.kotlin
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi
import org.junit.jupiter.api.Test

class RequestClassStructuralValidationTest : ApiBaseTest() {
    @Test
    fun `Name not ending in Request rejected`() {
        val request =
            kotlin(
                "GetUser.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                class GetUser
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "must end with 'Request' suffix and have a descriptive name"
    }

    @Test
    fun `Name exactly Request rejected`() {
        val request =
            kotlin(
                "Request.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                class Request
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "must end with 'Request' suffix and have a descriptive name"
    }

    @Test
    fun `Non-data class with properties rejected`() {
        val request =
            kotlin(
                "GetUserRequest.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                class GetUserRequest(val page: Int = 0)
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "must be a data class"
    }

    @Test
    fun `Non-data class with no properties accepted (marker class)`() {
        val request =
            kotlin(
                "DeleteSessionRequest.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.DELETE
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                @DELETE("/sessions")
                @Returns(success = Unit::class)
                @Serializable
                object DeleteSessionRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        assertSourceEquals(
            $$"""
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.api.ksp.test.generated

            import dev.kolibrium.api.core.ApiResponse
            import dev.kolibrium.api.core.EmptyResponse
            import io.ktor.client.HttpClient
            import io.ktor.client.request.delete
            import io.ktor.http.contentType
            import kotlin.String

            /**
             * HTTP client for the Test API.
             */
            public class TestClient(
              private val client: HttpClient,
              private val baseUrl: String,
            ) {
              /**
               * Performs a DELETE request to /sessions.
               */
              public suspend fun deleteSession(): EmptyResponse {
                val httpResponse = client.delete("$baseUrl/sessions")

                return ApiResponse(
                  status = httpResponse.status,
                  headers = httpResponse.headers,
                  contentType = httpResponse.contentType(),
                  body = Unit,
                )
              }
            }
            """,
            "TestClient.kt",
            kotlinCompilation,
        )
    }

    @Test
    fun `Abstract and sealed request classes rejected`() {
        val abstractRequest =
            kotlin(
                "AbstractRequest.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                abstract class GetUserRequest
                """.trimIndent(),
            )
        val compilation1 = getCompilation(validApiSpec, abstractRequest).compile()
        compilation1.exitCode shouldBe COMPILATION_ERROR
        compilation1.messages shouldContain "cannot be abstract, sealed, or inner"

        val sealedRequest =
            kotlin(
                "SealedRequest.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class)
                @Serializable
                sealed class GetUserRequest
                """.trimIndent(),
            )
        val compilation2 = getCompilation(validApiSpec, sealedRequest).compile()
        compilation2.exitCode shouldBe COMPILATION_ERROR
        compilation2.messages shouldContain "cannot be abstract, sealed, or inner"
    }

    @Test
    fun `Inner class request is not discovered by package scan`() {
        // Discovery iterates top-level file declarations only, so an inner class
        // inside another class is never passed to the validator. This test confirms
        // the inner class is silently ignored (no error, no generated method).
        val request =
            kotlin(
                "InnerRequest.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                class Outer {
                    @GET("/users")
                    @Returns(success = UserDto::class)
                    @Serializable
                    inner class GetUserRequest
                }
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe OK
        compilation.messages shouldContain "No request classes found"
    }

    @Test
    fun `Object request class with properties rejected`() {
        val request =
            kotlin(
                "ObjectWithProps.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import dev.kolibrium.api.ksp.annotations.Path
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                import kotlinx.serialization.Transient
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users/{id}")
                @Returns(success = UserDto::class)
                @Serializable
                object GetUserRequest {
                    @Path @Transient val id: Int = 0
                }
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "cannot have properties"
    }

    @Test
    fun `Multiple HTTP method annotations rejected`() {
        val request =
            kotlin(
                "GetUserRequest.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @POST("/users")
                @Returns(success = UserDto::class)
                @Serializable
                class GetUserRequest
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "multiple HTTP method annotations"
    }

    @Test
    fun `Blank path rejected`() {
        val emptyPath =
            kotlin(
                "EmptyPath.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("")
                @Returns(success = UserDto::class)
                @Serializable
                class GetUsersRequest
                """.trimIndent(),
            )
        val compilation1 = getCompilation(validApiSpec, emptyPath).compile()
        compilation1.exitCode shouldBe COMPILATION_ERROR
        compilation1.messages shouldContain "must specify a path"

        val blankPath =
            kotlin(
                "BlankPath.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("   ")
                @Returns(success = UserDto::class)
                @Serializable
                class GetUsersRequest
                """.trimIndent(),
            )
        val compilation2 = getCompilation(validApiSpec, blankPath).compile()
        compilation2.exitCode shouldBe COMPILATION_ERROR
        compilation2.messages shouldContain "must specify a path"
    }

    @Test
    fun `Missing @Returns annotation rejected`() {
        val request =
            kotlin(
                "GetUsersRequest.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import kotlinx.serialization.Serializable
                @GET("/users")
                @Serializable
                class GetUsersRequest
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "must have @Returns annotation"
    }
}
