/*
 * Copyright 2023-2025 Attila Fazekas & contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@file:OptIn(ExperimentalCompilerApi::class)

package dev.kolibrium.api.ksp.processors

import com.tschuchort.compiletesting.KotlinCompilation.ExitCode.COMPILATION_ERROR
import com.tschuchort.compiletesting.KotlinCompilation.ExitCode.OK
import com.tschuchort.compiletesting.SourceFile.Companion.kotlin
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi
import org.junit.jupiter.api.Test

class ReturnTypeValidationTest : ApiBaseTest() {
    @Test
    fun `Returns Unit generates EmptyResponse`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.DELETE
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                @DELETE("/sessions")
                @Returns(success = Unit::class)
                @Serializable
                class DeleteSessionRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        assertSourceEquals(
            $$"""
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.api.ksp.test.generated

            import dev.kolibrium.api.core.ApiResponse
            import dev.kolibrium.api.core.EmptyResponse
            import io.ktor.client.HttpClient
            import io.ktor.client.request.delete
            import io.ktor.http.contentType
            import kotlin.String

            public class TestClient(
              private val client: HttpClient,
              private val baseUrl: String,
            ) {
              public suspend fun deleteSession(): EmptyResponse {
                val httpResponse = client.delete("$baseUrl/sessions")

                return ApiResponse(
                  status = httpResponse.status,
                  headers = httpResponse.headers,
                  contentType = httpResponse.contentType(),
                  body = Unit,
                )
              }
            }
            """,
            "TestClient.kt",
            kotlinCompilation,
        )
    }

    @Test
    fun `Success type not Serializable is rejected`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                class NotSerializable(val id: Int)
                @GET("/users")
                @Returns(success = NotSerializable::class)
                @Serializable
                class GetUsersRequest
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "is not @Serializable"
    }

    @Test
    fun `Returns error Nothing is treated as no error type`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                @Serializable
                data class UserDto(val id: Int)
                @GET("/users")
                @Returns(success = UserDto::class, error = Nothing::class)
                @Serializable
                class GetUsersRequest
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        assertSourceEquals(
            $$"""
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.api.ksp.test.generated

            import dev.kolibrium.api.core.ApiResponse
            import dev.kolibrium.api.ksp.test.models.UserDto
            import io.ktor.client.HttpClient
            import io.ktor.client.call.body
            import io.ktor.client.request.`get`
            import io.ktor.http.contentType
            import kotlin.String

            public class TestClient(
              private val client: HttpClient,
              private val baseUrl: String,
            ) {
              public suspend fun getUsers(): ApiResponse<UserDto> {
                val httpResponse = client.get("$baseUrl/users")

                return ApiResponse(
                  status = httpResponse.status,
                  headers = httpResponse.headers,
                  contentType = httpResponse.contentType(),
                  body = httpResponse.body(),
                )
              }
            }
            """,
            "TestClient.kt",
            kotlinCompilation,
        )
    }

    @Test
    fun `Error type not Serializable is rejected`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.GET
                import dev.kolibrium.api.ksp.annotations.Returns
                import kotlinx.serialization.Serializable
                @Serializable
                data class SuccessDto(val id: Int)
                class NotSerializable(val msg: String)
                @GET("/users")
                @Returns(success = SuccessDto::class, error = NotSerializable::class)
                @Serializable
                class GetUsersRequest
                """.trimIndent(),
            )
        val compilation = getCompilation(validApiSpec, request).compile()
        compilation.exitCode shouldBe COMPILATION_ERROR
        compilation.messages shouldContain "is not @Serializable"
    }

    @Test
    fun `Valid success and error types generate sealed result type`() {
        val request =
            kotlin(
                "Requests.kt",
                """
                package dev.kolibrium.api.ksp.test.models
                import dev.kolibrium.api.ksp.annotations.*
                import kotlinx.serialization.Serializable
                import kotlinx.serialization.Transient
                @Serializable
                data class SuccessDto(val id: Int)
                @Serializable
                data class ApiError(val message: String)
                @GET("/users/{id}")
                @Returns(success = SuccessDto::class, error = ApiError::class)
                @Serializable
                data class GetUserRequest(
                    @Path @Transient val id: Int = 0
                )
                """.trimIndent(),
            )
        val kotlinCompilation = getCompilation(validApiSpec, request)
        val compilation = kotlinCompilation.compile()
        compilation.exitCode shouldBe OK
        val source = kotlinCompilation.getGeneratedSource("TestClient.kt")
        source shouldContain "public sealed interface GetUserResult"
        source shouldContain "public fun requireSuccess(): Success"
        source shouldContain "public fun requireError(): Error"
        source shouldContain "public data class Success("
        source shouldContain "public val `data`: SuccessDto,"
        source shouldContain "public val response: HttpResponse,"
        source shouldContain ") : GetUserResult"
        source shouldContain "public data class Error("
        source shouldContain "public val `data`: ApiError,"
        source shouldContain "public suspend fun getUser(id: Int): GetUserResult"
        source shouldContain "GetUserResult.Success("
        source shouldContain "GetUserResult.Error("
        source shouldContain "httpResponse.bodyAsText()"
        source shouldContain "rawBody.take(500)"
    }
}
