name: Runs Gradle
description: Runs a given Gradle task
inputs:
  arguments:
    required: false
    description: Gradle arguments
    default: build
runs:
  using: "composite"
  steps:
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          ${{ inputs.arguments }}