name: Runs Gradle
description: Runs a given Gradle task
inputs:
  arguments:
    required: false
    description: Gradle arguments
    default: build
  cache-disabled:
    required: false
    description: Disable caching
    default: false
runs:
  using: "composite"
  steps:
    - name: Run a Gradle task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          ${{ inputs.arguments }}
        cache-disabled: ${{ inputs.cache-disabled }}