/*
 * Copyright 2023-2024 Attila Fazekas & contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@file:OptIn(ExperimentalCompilerApi::class)

package dev.kolibrium.ksp.processors

import com.tschuchort.compiletesting.KotlinCompilation.ExitCode.OK
import com.tschuchort.compiletesting.SourceFile.Companion.kotlin
import io.kotest.matchers.shouldBe
import org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi
import org.junit.jupiter.api.Test

class PageProcessorTest : ProcessorBaseTest() {
    @Test
    fun `class annotated with Page - no relative path set`() {
        val sourceFile =
            kotlin(
                "InventoryPage.kt",
                """
                package dev.kolibrium.ksp.processors.test

                import dev.kolibrium.ksp.annotations.Page

                @Page
                class InventoryPage
                """.trimIndent(),
            )

        val compilation = getCompilation(sourceFile)
        compilation.compile().exitCode shouldBe OK

        assertSourceEquals(
            """
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.ksp.processors.test.generated

            import dev.kolibrium.ksp.processors.test.InventoryPage
            import kotlin.Unit
            import org.openqa.selenium.WebDriver

            public fun WebDriver.inventoryPage(block: InventoryPage.() -> Unit) {
              InventoryPage().apply(block)
            }
            """.trimIndent(),
            actualFileName = "InventoryPage.kt",
            compilation = compilation,
        )
    }

    @Test
    fun `class annotated with Page - relative path set, useDsl = false`() {
        val sourceFile =
            kotlin(
                "InventoryPage.kt",
                """
                package dev.kolibrium.ksp.processors.test

                import dev.kolibrium.ksp.annotations.Page

                @Page("inventory.html")
                class InventoryPage
                """.trimIndent(),
            )

        val compilation = getCompilation(sourceFile)
        compilation.compile().exitCode shouldBe OK

        assertSourceEquals(
            """
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.ksp.processors.test.generated

            import dev.kolibrium.ksp.processors.test.InventoryPage
            import kotlin.Unit
            import org.openqa.selenium.WebDriver

            public fun WebDriver.inventoryPage(block: InventoryPage.() -> Unit) {
              get(${'"'}${'"'}${'"'}${'$'}{currentUrl}inventory.html${'"'}${'"'}${'"'})
              InventoryPage().apply(block)
            }
            """.trimIndent(),
            actualFileName = "InventoryPage.kt",
            compilation = compilation,
        )
    }

    @Test
    fun `class annotated with Page - relative path set, useDsl = true`() {
        val sourceFile =
            kotlin(
                "InventoryPage.kt",
                """
                package dev.kolibrium.ksp.processors.test

                import dev.kolibrium.ksp.annotations.Page

                @Page("inventory.html")
                class InventoryPage
                """.trimIndent(),
            )

        val compilation = getCompilation(sourceFile, useDsl = true)
        compilation.compile().exitCode shouldBe OK

        assertSourceEquals(
            """
            // Code generated by kolibrium-codegen. Do not edit.
            package dev.kolibrium.ksp.processors.test.generated

            import dev.kolibrium.dsl.selenium.interactions.navigateTo
            import dev.kolibrium.ksp.processors.test.InventoryPage
            import kotlin.Unit
            import org.openqa.selenium.WebDriver

            public fun WebDriver.inventoryPage(block: InventoryPage.() -> Unit) {
              navigateTo("inventory.html")
              InventoryPage().apply(block)
            }
            """.trimIndent(),
            actualFileName = "InventoryPage.kt",
            compilation = compilation,
        )
    }
}
