/*
 * Copyright 2023-2026 Attila Fazekas & contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.kolibrium.selenium.ksp.processors

import com.tschuchort.compiletesting.KotlinCompilation.ExitCode
import com.tschuchort.compiletesting.SourceFile.Companion.kotlin
import com.tschuchort.compiletesting.kspSourcesDir
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import org.junit.jupiter.api.Test

class TestHarnessGenerationTest : BaseTest() {
    @Test
    fun `harness file name, package, and header`() {
        val compilation = getCompilation(validSite)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.OK

        val source = compilation.getGeneratedSource("TestSiteTestHarness.kt")
        source shouldContain "package dev.kolibrium.selenium.ksp.test.generated"
        source shouldContain "Code generated by kolibrium-codegen. Do not edit."
    }

    @Test
    fun `no-setup overload signature and delegation`() {
        val compilation = getCompilation(validSite)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.OK

        val source = compilation.getGeneratedSource("TestSiteTestHarness.kt")
        source shouldContain "fun testSiteTest("
        source shouldContain "driverFactory: DriverFactory"
        source shouldContain "keepBrowserOpen: Boolean = false"
        source shouldContain "block: suspend SiteEntry<TestSite>.(Unit) -> Unit"
        source shouldContain "seleniumTest(site = TestSite"
    }

    @Test
    fun `setUp tearDown overload signature`() {
        val compilation = getCompilation(validSite)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.OK

        val source = compilation.getGeneratedSource("TestSiteTestHarness.kt")
        source shouldContain "fun <T> testSiteTest("
        source shouldContain "setUp: suspend () -> T"
        source shouldContain "tearDown: suspend (T) -> Unit = {}"
        source shouldContain "block: suspend SiteEntry<TestSite>.(T) -> Unit"
    }

    @Test
    fun `non-object class fails`() {
        val source =
            kotlin(
                "BadSite.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.core.SeleniumSite
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                class BadSite : SeleniumSite(baseUrl = "https://example.com")
                """.trimIndent(),
            )

        val result = getCompilation(source).compile()

        result.exitCode shouldBe ExitCode.COMPILATION_ERROR
    }

    @Test
    fun `non-SeleniumSite supertype fails`() {
        val source =
            kotlin(
                "BadSite.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                object BadSite
                """.trimIndent(),
            )

        val result = getCompilation(source).compile()

        result.exitCode shouldBe ExitCode.COMPILATION_ERROR
    }

    @Test
    fun `no annotation produces no generation`() {
        val source =
            kotlin(
                "PlainSite.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.core.SeleniumSite
                object PlainSite : SeleniumSite(baseUrl = "https://example.com")
                """.trimIndent(),
            )

        val compilation = getCompilation(source)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.OK

        val generatedFiles =
            compilation.kspSourcesDir
                .walkTopDown()
                .filter { it.isFile }
                .toList()

        generatedFiles shouldBe emptyList()
    }

    @Test
    fun `function name derivation`() {
        val source =
            kotlin(
                "BrowserStackDemo.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.core.SeleniumSite
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                object BrowserStackDemo : SeleniumSite(baseUrl = "https://bstackdemo.com")
                """.trimIndent(),
            )

        val compilation = getCompilation(source)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.OK

        val generatedSource = compilation.getGeneratedSource("BrowserStackDemoTestHarness.kt")
        generatedSource shouldContain "fun browserStackDemoTest("
    }
}
