/*
 * Copyright 2023-2026 Attila Fazekas & contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.kolibrium.selenium.ksp.processors

import com.tschuchort.compiletesting.KotlinCompilation.ExitCode
import com.tschuchort.compiletesting.SourceFile.Companion.kotlin
import com.tschuchort.compiletesting.kspSourcesDir
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import org.junit.jupiter.api.Test

class TestHarnessGenerationTest : BaseTest() {
    @Test
    fun `harness file name, package, and header`() {
        val compilation = getCompilation(validSite)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.OK

        val source = compilation.getGeneratedSource("TestSiteTestHarness.kt")
        source shouldContain "package dev.kolibrium.selenium.ksp.test.generated"
        source shouldContain "Code generated by kolibrium-codegen. Do not edit."
    }

    @Test
    fun `no-setup overload signature and delegation`() {
        val compilation = getCompilation(validSite)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.OK

        val source = compilation.getGeneratedSource("TestSiteTestHarness.kt")
        source shouldContain "fun testSiteTest("
        source shouldContain "driverFactory: DriverFactory"
        source shouldContain "keepBrowserOpen: Boolean = false"
        source shouldContain "block: suspend SiteEntry<TestSite>.() -> Unit"
        source shouldContain "seleniumTest(site = TestSite"
    }

    @Test
    fun `setUp tearDown overload signature`() {
        val compilation = getCompilation(validSite)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.OK

        val source = compilation.getGeneratedSource("TestSiteTestHarness.kt")
        source shouldContain "fun <T> testSiteTest("
        source shouldContain "setUp: suspend () -> T"
        source shouldContain "tearDown: suspend (T) -> Unit = {}"
        source shouldContain "block: suspend SiteEntry<TestSite>.(T) -> Unit"
    }

    @Test
    fun `non-object class fails`() {
        val source =
            kotlin(
                "BadSite.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.core.SeleniumSite
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                class BadSite : SeleniumSite(baseUrl = "https://example.com")
                """.trimIndent(),
            )

        val result = getCompilation(source).compile()

        result.exitCode shouldBe ExitCode.COMPILATION_ERROR
    }

    @Test
    fun `non-SeleniumSite supertype fails`() {
        val source =
            kotlin(
                "BadSite.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                object BadSite
                """.trimIndent(),
            )

        val result = getCompilation(source).compile()

        result.exitCode shouldBe ExitCode.COMPILATION_ERROR
    }

    @Test
    fun `no annotation produces no generation`() {
        val source =
            kotlin(
                "PlainSite.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.core.SeleniumSite
                object PlainSite : SeleniumSite(baseUrl = "https://example.com")
                """.trimIndent(),
            )

        val compilation = getCompilation(source)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.OK

        val generatedFiles =
            compilation.kspSourcesDir
                .walkTopDown()
                .filter { it.isFile }
                .toList()

        generatedFiles shouldBe emptyList()
    }

    @Test
    fun `function name derivation`() {
        val source =
            kotlin(
                "BrowserStackDemo.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.core.SeleniumSite
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                object BrowserStackDemo : SeleniumSite(baseUrl = "https://bstackdemo.com")
                """.trimIndent(),
            )

        val compilation = getCompilation(source)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.OK

        val generatedSource = compilation.getGeneratedSource("BrowserStackDemoTestHarness.kt")
        generatedSource shouldContain "fun browserStackDemoTest("
    }

    @Test
    fun `duplicate site names differing only in case both produce errors`() {
        val site1 =
            kotlin(
                "TestSite1.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.core.SeleniumSite
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                object MySite : SeleniumSite(baseUrl = "https://example.com")
                """.trimIndent(),
            )
        val site2 =
            kotlin(
                "TestSite2.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.core.SeleniumSite
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                object Mysite : SeleniumSite(baseUrl = "https://example.org")
                """.trimIndent(),
            )

        val compilation = getCompilation(site1, site2)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.COMPILATION_ERROR

        val generatedFiles =
            compilation.kspSourcesDir
                .walkTopDown()
                .filter { it.isFile }
                .toList()

        generatedFiles shouldBe emptyList()
    }

    @Test
    fun `multiple valid sites produce separate harness files`() {
        val site1 =
            kotlin(
                "AlphaSite.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.core.SeleniumSite
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                object AlphaSite : SeleniumSite(baseUrl = "https://alpha.com")
                """.trimIndent(),
            )
        val site2 =
            kotlin(
                "BetaSite.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.core.SeleniumSite
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                object BetaSite : SeleniumSite(baseUrl = "https://beta.com")
                """.trimIndent(),
            )

        val compilation = getCompilation(site1, site2)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.OK

        val alphaSource = compilation.getGeneratedSource("AlphaSiteTestHarness.kt")
        alphaSource shouldContain "fun alphaSiteTest("

        val betaSource = compilation.getGeneratedSource("BetaSiteTestHarness.kt")
        betaSource shouldContain "fun betaSiteTest("
    }

    @Test
    fun `uppercase acronym site name produces expected function name`() {
        val source =
            kotlin(
                "APIDemo.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.core.SeleniumSite
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                object APIDemo : SeleniumSite(baseUrl = "https://apidemo.com")
                """.trimIndent(),
            )

        val compilation = getCompilation(source)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.OK

        val generatedSource = compilation.getGeneratedSource("APIDemoTestHarness.kt")
        generatedSource shouldContain "fun aPIDemoTest("
    }

    @Test
    fun `indirect SeleniumSite subclass fails`() {
        val base =
            kotlin(
                "MySiteBase.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.core.SeleniumSite
                abstract class MySiteBase(url: String) : SeleniumSite(baseUrl = url)
                """.trimIndent(),
            )
        val site =
            kotlin(
                "IndirectSite.kt",
                """
                package dev.kolibrium.selenium.ksp.test
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                object IndirectSite : MySiteBase("https://example.com")
                """.trimIndent(),
            )

        val result = getCompilation(base, site).compile()

        result.exitCode shouldBe ExitCode.COMPILATION_ERROR
    }

    @Test
    fun `exact duplicate site names in different packages both produce errors`() {
        val site1 =
            kotlin(
                "Site1.kt",
                """
                package dev.kolibrium.selenium.ksp.test.a
                import dev.kolibrium.selenium.core.SeleniumSite
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                object DemoSite : SeleniumSite(baseUrl = "https://a.com")
                """.trimIndent(),
            )
        val site2 =
            kotlin(
                "Site2.kt",
                """
                package dev.kolibrium.selenium.ksp.test.b
                import dev.kolibrium.selenium.core.SeleniumSite
                import dev.kolibrium.selenium.ksp.annotations.GenerateTestHarness
                @GenerateTestHarness
                object DemoSite : SeleniumSite(baseUrl = "https://b.com")
                """.trimIndent(),
            )

        val compilation = getCompilation(site1, site2)
        val result = compilation.compile()

        result.exitCode shouldBe ExitCode.COMPILATION_ERROR
    }
}
