name: Set up JDK
description: Sets up the JDK required to run Gradle tasks
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20'
