name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  call-change-detection:
    uses: ./.github/workflows/change_detection.yml
    permissions:
      pull-requests: read

  build:
    needs: call-change-detection
    if: ${{ needs.call-change-detection.outputs.kotlin == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-jdk

      - name: Install zip
        uses: montudor/action-zip@v1

      - uses: ./.github/actions/run-gradle

      - name: Zip output
        run: zip -qq -r test-reports.zip test
        working-directory: /home/runner/work/kolibrium/kolibrium/dsl/build/reports/tests

      - uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: /home/runner/work/kolibrium/kolibrium/dsl/build/reports/tests/test-reports.zip
