name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  call-change-detection:
    uses: ./.github/workflows/change_detection.yml

  build:
    needs: call-change-detection
    if: ${{ needs.call-change-detection.outputs.kotlin == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-jdk

      - uses: ./.github/actions/run-gradle
