name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  call-change-detection:
    uses: ./.github/workflows/change_detection.yml
    permissions:
      pull-requests: read

  build:
    needs: call-change-detection
    if: ${{ needs.call-change-detection.outputs.kotlin == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-jdk

      - name: Install zip
        uses: montudor/action-zip@v1

      - uses: ./.github/actions/run-gradle

      - name: Zip output - Core
        if: success() || failure()
        run: zip -qq -r test-reports-core.zip test
        working-directory: /home/runner/work/kolibrium/kolibrium/core/build/reports/tests

      - name: Zip output - DSL
        if: success() || failure()
        run: zip -qq -r test-reports-dsl.zip test
        working-directory: /home/runner/work/kolibrium/kolibrium/dsl/build/reports/tests

      - name: Zip output - KSP
        if: success() || failure()
        run: zip -qq -r test-reports-ksp.zip test
        working-directory: /home/runner/work/kolibrium/kolibrium/ksp/processors/build/reports/tests

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-reports-core
          path: |
            /home/runner/work/kolibrium/kolibrium/core/build/reports/tests/test-reports-core.zip
            /home/runner/work/kolibrium/kolibrium/dsl/build/reports/tests/test-reports-dsl.zip
            /home/runner/work/kolibrium/kolibrium/ksp/processors/build/reports/tests/test-reports-ksp.zip
