name: RefreshVersions on PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  refresh-versions:
    name: Run RefreshVersions
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    env:
      DEPENDENCY_UPDATE_BRANCH: "dependency-update"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "main"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2
        with:
          branch: ${{ env.DEPENDENCY_UPDATE_BRANCH }}

      - name: Run refreshVersions
        uses: gradle/gradle-build-action@v2
        with:
          arguments: refreshVersions

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "noreply@github.com"
          message: "Update versions.properties"
          new_branch: ${{ env.DEPENDENCY_UPDATE_BRANCH }}

      - name: Create Pull Request
        run: >
          gh pr create
          --head ${{ env.DEPENDENCY_UPDATE_BRANCH }}
          --base main
          --title "Update dependencies"
          --body "[refreshVersions](https://github.com/Splitties/refreshVersions) has found library updates."
          --label "dependency updates"
          --reviewer attila-fazekas
