name: RefreshVersions PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:

  Refresh-Version:
    name: Run RefreshVersions
    permissions: write-all
    runs-on: ubuntu-latest
    
    env:
      MAIN_BRANCH: "main"
      DEPENDENCY_UPDATE_BRANCH: "dependency-update"
      
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.MAIN_BRANCH }}          
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'      

      - uses: peterjgrainger/action-create-branch@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.DEPENDENCY_UPDATE_BRANCH }}

      - name: Run RefreshVersions
        run: ./gradlew refreshVersions

      - uses: EndBug/add-and-commit@v9
        name: Commit
        with:
          author_name: "GitHub Actions"
          author_email: "noreply@github.com"
          new_branch: ${{ env.DEPENDENCY_UPDATE_BRANCH }}
          message: "Update versions.properties"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: 
          gh pr create --head ${{ env.DEPENDENCY_UPDATE_BRANCH }} --base main --title "Update dependencies" --fill --draft --reviewer attila-fazekas
