name: RefreshVersions on PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  refresh-versions:
    name: Run RefreshVersions
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    
    env:
      DEPENDENCY_UPDATE_BRANCH: "dependency-update"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "main"

      - uses: ./.github/actions/setup-jdk

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.3.0
        with:
          branch: ${{ env.DEPENDENCY_UPDATE_BRANCH }}

      - name: Run refreshVersions
        uses: ./.github/actions/run-gradle
        with:
          arguments: refreshVersions

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "noreply@github.com"
          message: "Update versions.properties"
          new_branch: ${{ env.DEPENDENCY_UPDATE_BRANCH }}

      - name: Create Pull Request
        run: >
          gh pr create
          --head ${{ env.DEPENDENCY_UPDATE_BRANCH }}
          --base main
          --title "Update dependencies"
          --body "[refreshVersions](https://github.com/Splitties/refreshVersions) has found library updates."
          --label "dependency update"
